/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsHontalDeliveryRouteImport } from './routes/products.hontal-delivery'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesBusinessActivationRouteImport } from './routes/services.business-activation'
import { Route as ServicesCustomOperationalSystemsRouteImport } from './routes/services.custom-operational-systems'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHontalDeliveryRoute = ProductsHontalDeliveryRouteImport.update({
  id: '/products/hontal-delivery',
  path: '/products/hontal-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessActivationRoute =
  ServicesBusinessActivationRouteImport.update({
    id: '/services/business-activation',
    path: '/services/business-activation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomOperationalSystemsRoute =
  ServicesCustomOperationalSystemsRouteImport.update({
    id: '/services/custom-operational-systems',
    path: '/services/custom-operational-systems',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/products/hontal-delivery': typeof ProductsHontalDeliveryRoute
  '/services/business-activation': typeof ServicesBusinessActivationRoute
  '/services/custom-operational-systems': typeof ServicesCustomOperationalSystemsRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/products/hontal-delivery': typeof ProductsHontalDeliveryRoute
  '/services/business-activation': typeof ServicesBusinessActivationRoute
  '/services/custom-operational-systems': typeof ServicesCustomOperationalSystemsRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/portfolio': typeof PortfolioRoute
  '/products/hontal-delivery': typeof ProductsHontalDeliveryRoute
  '/services/business-activation': typeof ServicesBusinessActivationRoute
  '/services/custom-operational-systems': typeof ServicesCustomOperationalSystemsRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/portfolio'
    | '/products/hontal-delivery'
    | '/services/business-activation'
    | '/services/custom-operational-systems'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/portfolio'
    | '/products/hontal-delivery'
    | '/services/business-activation'
    | '/services/custom-operational-systems'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/portfolio'
    | '/products/hontal-delivery'
    | '/services/business-activation'
    | '/services/custom-operational-systems'
    | '/products/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  PortfolioRoute: typeof PortfolioRoute
  ProductsHontalDeliveryRoute: typeof ProductsHontalDeliveryRoute
  ServicesBusinessActivationRoute: typeof ServicesBusinessActivationRoute
  ServicesCustomOperationalSystemsRoute: typeof ServicesCustomOperationalSystemsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hontal-delivery': {
      id: '/products/hontal-delivery'
      path: '/products/hontal-delivery'
      fullPath: '/products/hontal-delivery'
      preLoaderRoute: typeof ProductsHontalDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-activation': {
      id: '/services/business-activation'
      path: '/services/business-activation'
      fullPath: '/services/business-activation'
      preLoaderRoute: typeof ServicesBusinessActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-operational-systems': {
      id: '/services/custom-operational-systems'
      path: '/services/custom-operational-systems'
      fullPath: '/services/custom-operational-systems'
      preLoaderRoute: typeof ServicesCustomOperationalSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  PortfolioRoute: PortfolioRoute,
  ProductsHontalDeliveryRoute: ProductsHontalDeliveryRoute,
  ServicesBusinessActivationRoute: ServicesBusinessActivationRoute,
  ServicesCustomOperationalSystemsRoute: ServicesCustomOperationalSystemsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
